version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db.json:/tmp/db.json
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379